name: go test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: run go tests
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: set up go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    - name: install dependencies
      run: |
        ./scripts/build.sh
    - name: run tests
      run: |
        ./scripts/test.sh
